apiVersion: 1

policies:
  - orgId: 1
    receiver: 'MR.DarkPromth Slack Alerts'
    group_by: ['alertname', 'grafana_folder', 'severity']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: 'MR.DarkPromth Slack Alerts'
        matchers:
          - label: severity
            match: critical
        group_wait: 10s
        group_interval: 1m
        repeat_interval: 1h
