input {
  tcp {
    port => 5000
    codec => json
  }
  file {
    path => "/app/logs/*.log"
    start_position => "beginning"
  }
}

filter {
  if [type] == "api_log" {
    json {
      source => "message"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "mrdarkpromth-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
