#!/bin/bash
# VPS Health Monitoring Script for Mr.DarkPromth
# Auto-generated by Manus AI Agent

set -euo pipefail

# Colors for output
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Thresholds
DISK_THRESHOLD=80
MEMORY_THRESHOLD=85
SWAP_THRESHOLD=70
LOAD_THRESHOLD=2.0

# Log file
LOG_FILE="/opt/mrdarkpromth/logs/health_monitor.log"
ALERT_FILE="/opt/mrdarkpromth/logs/alerts.log"

# Function to log messages
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

# Function to send alert
send_alert() {
    local severity=$1
    local message=$2
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [$severity] $message" | tee -a "$ALERT_FILE"
    
    # TODO: Send to Slack via manus-mcp-cli
    # manus-mcp-cli tool call slack_send_message --server slack --input "{\"channel_id\": \"ALERTS_CHANNEL\", \"text\": \"[$severity] $message\"}"
}

# Check disk usage
check_disk() {
    log "Checking disk usage..."
    
    local disk_usage=$(df / | tail -1 | awk '{print $5}' | sed 's/%//')
    local disk_avail=$(df -h / | tail -1 | awk '{print $4}')
    
    echo -e "Disk Usage: ${disk_usage}% (Available: ${disk_avail})"
    
    if [ "$disk_usage" -ge "$DISK_THRESHOLD" ]; then
        echo -e "${RED}⚠️  ALERT: Disk usage is ${disk_usage}%${NC}"
        send_alert "CRITICAL" "Disk usage is ${disk_usage}% (threshold: ${DISK_THRESHOLD}%)"
        return 1
    elif [ "$disk_usage" -ge $((DISK_THRESHOLD - 10)) ]; then
        echo -e "${YELLOW}⚠️  WARNING: Disk usage is ${disk_usage}%${NC}"
        send_alert "WARNING" "Disk usage is ${disk_usage}%"
    else
        echo -e "${GREEN}✅ Disk usage is healthy: ${disk_usage}%${NC}"
    fi
}

# Check memory usage
check_memory() {
    log "Checking memory usage..."
    
    local mem_total=$(free | grep Mem | awk '{print $2}')
    local mem_used=$(free | grep Mem | awk '{print $3}')
    local mem_percent=$((mem_used * 100 / mem_total))
    
    local swap_total=$(free | grep Swap | awk '{print $2}')
    local swap_used=$(free | grep Swap | awk '{print $3}')
    local swap_percent=0
    
    if [ "$swap_total" -gt 0 ]; then
        swap_percent=$((swap_used * 100 / swap_total))
    fi
    
    echo -e "Memory Usage: ${mem_percent}%"
    echo -e "Swap Usage: ${swap_percent}%"
    
    if [ "$mem_percent" -ge "$MEMORY_THRESHOLD" ]; then
        echo -e "${RED}⚠️  ALERT: Memory usage is ${mem_percent}%${NC}"
        send_alert "CRITICAL" "Memory usage is ${mem_percent}% (threshold: ${MEMORY_THRESHOLD}%)"
        return 1
    elif [ "$swap_percent" -ge "$SWAP_THRESHOLD" ]; then
        echo -e "${YELLOW}⚠️  WARNING: Swap usage is ${swap_percent}%${NC}"
        send_alert "WARNING" "Swap usage is ${swap_percent}%"
    else
        echo -e "${GREEN}✅ Memory usage is healthy: ${mem_percent}%${NC}"
    fi
}

# Check system load
check_load() {
    log "Checking system load..."
    
    local load_1min=$(uptime | awk -F'load average:' '{print $2}' | awk -F',' '{print $1}' | xargs)
    local cpu_count=$(nproc)
    
    echo -e "Load Average (1min): ${load_1min} (CPUs: ${cpu_count})"
    
    # Compare load with threshold
    if (( $(echo "$load_1min > $LOAD_THRESHOLD" | bc -l) )); then
        echo -e "${YELLOW}⚠️  WARNING: High system load: ${load_1min}${NC}"
        send_alert "WARNING" "High system load: ${load_1min}"
    else
        echo -e "${GREEN}✅ System load is healthy: ${load_1min}${NC}"
    fi
}

# Check Docker containers
check_docker() {
    log "Checking Docker containers..."
    
    local total_containers=$(docker ps -a | wc -l)
    local running_containers=$(docker ps | wc -l)
    local unhealthy_containers=$(docker ps --filter "health=unhealthy" | wc -l)
    
    echo -e "Docker Containers: ${running_containers}/$((total_containers - 1)) running"
    
    if [ "$unhealthy_containers" -gt 1 ]; then
        echo -e "${RED}⚠️  ALERT: ${unhealthy_containers} unhealthy containers${NC}"
        send_alert "CRITICAL" "${unhealthy_containers} Docker containers are unhealthy"
        docker ps --filter "health=unhealthy" --format "table {{.Names}}\t{{.Status}}"
        return 1
    else
        echo -e "${GREEN}✅ All Docker containers are healthy${NC}"
    fi
}

# Check Docker disk usage
check_docker_disk() {
    log "Checking Docker disk usage..."
    
    echo -e "\nDocker System Usage:"
    docker system df
    
    # Check for dangling images
    local dangling_count=$(docker images -f "dangling=true" -q | wc -l)
    
    if [ "$dangling_count" -gt 10 ]; then
        echo -e "${YELLOW}⚠️  WARNING: ${dangling_count} dangling Docker images${NC}"
        send_alert "WARNING" "${dangling_count} dangling Docker images found"
    fi
}

# Auto cleanup function
auto_cleanup() {
    log "Running auto cleanup..."
    
    echo -e "\n${YELLOW}Running automatic cleanup...${NC}"
    
    # Remove dangling images
    echo "Removing dangling images..."
    docker image prune -f
    
    # Remove old logs (older than 7 days)
    echo "Removing old logs..."
    find /opt/mrdarkpromth/logs -name "*.log" -mtime +7 -delete
    
    # Remove old backups (older than 30 days)
    echo "Removing old backups..."
    find /opt/mrdarkpromth/backups -name "*.sql" -mtime +30 -delete
    
    echo -e "${GREEN}✅ Cleanup completed${NC}"
    log "Auto cleanup completed"
}

# Main function
main() {
    echo "========================================"
    echo "  Mr.DarkPromth VPS Health Monitor"
    echo "  $(date '+%Y-%m-%d %H:%M:%S')"
    echo "========================================"
    echo ""
    
    local status=0
    
    check_disk || status=1
    echo ""
    
    check_memory || status=1
    echo ""
    
    check_load
    echo ""
    
    check_docker || status=1
    echo ""
    
    check_docker_disk
    echo ""
    
    # Run auto cleanup if disk usage is high
    local disk_usage=$(df / | tail -1 | awk '{print $5}' | sed 's/%//')
    if [ "$disk_usage" -ge $((DISK_THRESHOLD - 5)) ]; then
        auto_cleanup
    fi
    
    echo "========================================"
    if [ $status -eq 0 ]; then
        echo -e "${GREEN}✅ All health checks passed${NC}"
    else
        echo -e "${RED}⚠️  Some health checks failed${NC}"
    fi
    echo "========================================"
    
    return $status
}

# Run main function
main "$@"
